from enum import Enum


class Amenity(Enum):
    PAPER_TOWEL = 0
    AIR_DRYER = 1
    SOAP = 2
    WHEELCHAIR_ACCESSIBLE = 3
    AUTOMATIC_SINK = 4
    AUTOMATIC_TOILET = 5
    AUTOMATIC_PAPER_TOWEL = 6
    AUTOMATIC_DRYER = 7
    SHOWER = 8
    URINAL = 9
    PAPER_SEAT_COVERS = 10
    HYGIENE_PRODUCTS = 11
    NEEDLE_DISPOSAL = 12
    CONTRACEPTION = 13
    BATHROOM_ATTENDENT = 14
    PERFUME_COLOGNE = 15
    LOTION = 16
