service: Throne-Backend

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: handler.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  timeout: 10
  environment:
    IS_LAMBDA: true
    DB_HOSTNAME: "${opt:stage}-db.findmythrone.com"
    DB_PASSWORD: "${env:DB_PASSWORD}"

functions:
  api:
    handler: wsgi_handler.handler
    reservedConcurrency: 60
    events:
      - http: 
          method: ANY 
          path: /
          cors: true
      - http: 
          method: ANY
          path: '{proxy+}'
          cors: true

package:
  exclude:
  - "__pycache__/**"
  - ".vscode/**"
  - ".github/**"
  - ".git/**"
  - "venv/**"
  - "node_modules/**"
  - "db-scripts/**"
  - "tests/**"
  - ".gitignore"
  - ".env"
  - "docs/**"
  - requirements.txt
  - LICENSE
  - CODEOWNERS
  - README.md
  - package.json
  - package-lock.json
  - tox.ini
  
